"""
Story Prompt Generator — Generate AI video storyboard prompts from GitHub trends.
Usage: python -m core_engine.src.story_prompt [--lang zh]
"""
import os
import argparse

from core_engine.src.utils.llm_client import call_llm

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _fetch_trends() -> list[dict]:
    """Fetch GitHub trending data using proper package import."""
    try:
        from crawler.src.github_spider import fetch_github_hot
        return fetch_github_hot()
    except Exception as e:
        print(f"  [WARN] Could not fetch trends: {e}")
        return []


def build_story_prompt(trend: dict, lang: str = "en") -> str:
    """Build a storyboard generation prompt from a single trend item."""
    lang_instruction = "Write all content in Chinese." if lang == "zh" else "Write all content in English."
    return (
        f"You are a short-video creative director.\n"
        f"Here is a currently trending topic:\n"
        f"- Platform: {trend['platform']}\n"
        f"- Title: {trend['title']}\n"
        f"- Popularity: {trend['hot_value']}\n\n"
        f"Based on this topic, generate a 4-scene short video storyboard containing:\n"
        f"1. Visual description for each scene\n"
        f"2. Corresponding narration/dialogue\n"
        f"3. Recommended visual style\n"
        f"{lang_instruction}\n"
        f"Return in JSON format as follows:\n"
        f'{{"scenes": [{{"scene_id": 1, "visual": "...", "narration": "...", "style": "..."}}]}}'
    )


def generate_stories(lang: str = "en"):
    """Fetch GitHub trends -> build story prompts -> call AI engine."""
    print("=== Fetching GitHub Trends ===")
    trends = _fetch_trends()

    if not trends:
        print("No trend data retrieved.")
        return []

    print(f"Retrieved {len(trends)} trends\n")

    results = []
    for i, trend in enumerate(trends, 1):
        print(f"--- [{i}/{len(trends)}] {trend['title']} ({trend['hot_value']}) ---")
        prompt = build_story_prompt(trend, lang)
        print(f"Prompt built, calling AI engine...\n")

        story = call_llm(prompt, lang=lang)
        print(story)
        print()

        results.append({
            "trend": trend,
            "prompt": prompt,
            "story": story
        })

    return results


if __name__ == "__main__":
    import json as _json
    parser = argparse.ArgumentParser(description="Generate storyboards from GitHub trends")
    parser.add_argument("--lang", default="en", choices=["en", "zh"], help="Output language (default: en)")
    args = parser.parse_args()
    results = generate_stories(lang=args.lang)

    # Save results to output folder
    out_dir = os.path.join(_ROOT, "core_engine", "output")
    os.makedirs(out_dir, exist_ok=True)

    # Save JSON
    json_path = os.path.join(out_dir, "storyboards.json")
    output = []
    for r in results:
        try:
            scenes = _json.loads(r["story"])
        except (_json.JSONDecodeError, TypeError):
            scenes = r["story"]
        output.append({"trend": r["trend"], "storyboard": scenes})
    with open(json_path, "w", encoding="utf-8") as f:
        _json.dump(output, f, ensure_ascii=False, indent=2)

    # Save Markdown
    md_path = os.path.join(out_dir, "storyboards.md")
    lines = ["# Generated Storyboards\n", "\n> Auto-generated by `story_prompt.py` from GitHub Trending data.\n\n---\n"]
    for idx, item in enumerate(output, 1):
        t = item["trend"]
        lines.append(f"\n## {idx}. {t['title']}\n")
        lines.append(f"\n| Field | Value |\n|-------|-------|\n| Platform | {t['platform']} |\n| Popularity | {t['hot_value']} |\n")
        sb = item["storyboard"]
        scenes = sb.get("scenes", []) if isinstance(sb, dict) else []
        for s in scenes:
            lines.append(f"\n### Scene {s['scene_id']}\n")
            lines.append(f"\n| | |\n|---|---|\n| **Visual** | {s['visual']} |\n| **Narration** | {s['narration']} |\n| **Style** | {s['style']} |\n")
        lines.append("\n---\n")
    with open(md_path, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"\nSaved to:\n  JSON: {json_path}\n  MD:   {md_path}")
